
#include QMK_KEYBOARD_H

#include "mazunki.h"
#include "unicode_map.h"

const uint16_t NONE = KC_NO;  // TODO: check type


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

[BASE] = LAYOUT_split_3x6_3(	
	KC_TAB,	KC_ESC,	KC_DOT,	KC_COMM,	KC_P,	KC_Y,		KC_F,	KC_G,	KC_C,	KC_R,	KC_L,	KC_SLSH,
	KC_LCTL,	KC_A,	KC_O,	KC_E,	KC_U,	KC_I,		KC_QUOT,	KC_D,	KC_H,	KC_T,	KC_N,	KC_S,	
	KC_LSFT,	KC_Q,	KC_J,	KC_K,	KC_X,	OSL(SYMBOLS),		KC_SCLN,	KC_B,	KC_M,	KC_W,	KC_V,	KC_Z,	
				KC_LGUI,	KC_SPC,	TO(MISC),		KC_ENT,	KC_BSPC,	OSL(INTER)
),

[INTER] = LAYOUT_split_3x6_3(	
	UU(0xE6),	(0xE6),	UC(0xE,	NONE,	NONE,	NONE,		NONE,	NONE,	NONE,	NONE,	NONE,	NONE,
	NONE,	NONE,	NONE,	NONE,	NONE,	NONE,		NONE,	NONE,	NONE,	NONE,	NONE,	NONE,	
	NONE,	NONE,	NONE,	NONE,	NONE,	NONE,		NONE,	NONE,	NONE,	NONE,	NONE,	NONE,	
				NONE,	NONE,	NONE,		NONE,	NONE,	NONE
),

[SYMBOLS] = LAYOUT_split_3x6_3(
	KC_TAB,	KC_6,	KC_7,	KC_8,	KC_9,	KC_0,		KC_CIRC,	KC_AMPR,	KC_ASTR,	KC_LPRN,	KC_RPRN,	KC_BSPC,
	KC_LCTL,	KC_1,	KC_2,	KC_3,	KC_4,	KC_5,		KC_MINS,	KC_EQL,	KC_LBRC,	KC_RBRC,	KC_BSLS,	KC_GRV,
	KC_LSFT,	NONE,	NONE,	NONE,	NONE,	NONE,		KC_UNDS,	KC_PLUS,	KC_LCBR,	KC_RCBR,	KC_PIPE,	KC_TILD,
				KC_LGUI,	TO(SYMBOLS),	TO(BASE),		KC_ENT,	KC_TRNS,	KC_RALT
),

[MISC] = LAYOUT_split_3x6_3(
	NONE,	NONE,	KC_Q,	KC_W,	KC_R,	KC_E,		NONE,	NONE,	NONE,	NONE,	NONE,	KC_PSCR,
	NONE,	KC_LCTL,	KC_A,	KC_S,	KC_D,	NONE,		KC_WH_L,	KC_WH_D,	KC_WH_U,	KC_WH_R,	KC_HOME,	KC_PGUP,
	NONE,	NONE,	NONE,	NONE,	KC_LCTL,	NONE,		KC_LEFT,	KC_DOWN,	KC_UP,	KC_RGHT,	KC_END,	KC_PGDN,
				KC_SPC,	KC_LSFT,	TO(BASE),		NONE,	NONE,	NONE
)
}


// vim: tabstop=15 shiftwidth=15 softtabstop=15 noexpandtab

